backup:
  files:
    - /mnt/c/backup
    - /mnt/c/backup
  database:
    type: mysql
    host: localhost
    user: user
    password: password
    name: dbname

cloud:
  provider: aws
  region: eu-west-2
  s3_bucket_name: my-temp-backup-bucket

webserver:
  server: IIS